#
# Copyright (c) 2022-2023 SMALLPROGRAM <https://github.com/smallprogram/OpenWrtAction>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/smallprogram/OpenWrtAction
# Description: Build OpenWrt using GitHub Actions
#

name: Build-OpenWrtSelfHost

on:
  repository_dispatch:
    types: [openwrt_source_update]
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
      is_display_detailed:
        description: 'Whether to display detailed information about compilation'
        required: false
        default: 'false'
      is_single_threaded:
        description: 'Whether single-threaded compilation'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Compile X86 Firmware
      id: compile
      run: |
        # cd /home/$USER
        # if [ ! -d "/home/$USER/OpenWrtAction" ]; then 
        #   git clone https://github.com/smallprogram/OpenWrtAction.git
        #   cd /home/$USER/OpenWrtAction
        # else 
        #   cd /home/$USER/OpenWrtAction
        #   git checkout main
        #   git fetch origin
        #   git reset --hard origin/main
        #   git clean -fdx
        # fi
        # echo "check source complate!"
        # cd /home/$USER/OpenWrtAction
        # bash wsl2op_lean.sh X86.config
        echo "status=success" >> $GITHUB_OUTPUT

    - name: rsync file to server
      if: steps.compile.outputs.status == 'success'
      run: |
        DATE_FOLDER=$(date +%Y%m%d_%H%M)
        echo $DATE_FOLDER
        sudo mkdir -p /mnt/windows_share/Openwrt/${DATE_FOLDER}
        sudo rsync -av  /home/$USER/lean_X86.config/bin/targets/x86/64/ /mnt/windows_share/Openwrt/${DATE_FOLDER}/
